version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
